SELECT 
    c.*,
    t.*,
    t.QTR_FY,
    t.ID AS Account_Id,
    t.TERRITORY AS GEO_NUMBER,
    t.RUKOBIA_SEGMENT_IV_GSK_TELE__C AS Segment
FROM AIP_FULL_COMMERCIAL.AIP_G_CALLS_BASE_TBL AS c
LEFT JOIN AIP_FULL_COMMERCIAL.AIP_HCP_TARGETS AS t
    ON c.TP_Quarter = t.QTR_FY
   AND c.Account_Id = t.ID
   AND c.GEO_NUMBER = t.TERRITORY;